### ISSUE TITLE
LWMA-2 Soon

### ISSUE THREAD

**Issue by FndNur1Labs** [Nur1Labs/Evo-Platform#1]
Implemented of LWMA-2

https://github.com/zawy12/difficulty-algorithms/issues/3

**Comment by Shiro20** [comment]
https://github.com/Nur1Labs/Evo-Platform/blob/master/src/core/Currency.cpp

we still unsure the attack this secure by

`if (timestamps.size() < 10) { //this when seed more updates than new user
		return 1000; //back to 1k diff for slow hash
}`

not

`if (timestamps.size() < 4) { //this when seed more updates than new user
		return 1; //back to 1k diff for slow hash
}`

need clarify this

**Comment by FndNur1Labs** [comment]
`return 1000;`

is something like that on patch karbowanec did. but we unsure that prevent nice hash big attack. LWMA-2 still on going. maybe upgrade level need on major

**Comment by Shiro20** [comment]
but karbowanec put 

`if (next_difficulty && testnet < 100000) { //less than 1k will did[change if already more than 1k]
		next_difficulty = 100000; //this diff reach 1k![change if already more than 1k]
}`

last time

**Comment by FndNur1Labs** [comment]
change logic this

`uint64_t initial_difficulty_guess = 1000; // Dev needs to select this. Guess low.
if (timestamps.size() <= static_cast<uint64_t>(N) )  {  
    return initial_difficulty_guess;  
}
`

to

`uint64_t initial_difficulty_guess = 100; // Dev needs to select this. Guess low.
if (timestamps.size() <= static_cast<uint64_t>(N) )  {  
    return initial_difficulty_guess;  
}`

to

`uint64_t initial_difficulty_guess = 1000; // Dev needs to select this. Guess low.
if (timestamps.size() <= static_cast<uint64_t>(N) )  {  
    return initial_difficulty_guess;  
}`

nice hash

**Comment by Shiro20** [comment]
put this

`uint64_t initial_difficulty_guess = 100; // Dev needs to select this. Guess low.
if (timestamps.size() <= 10 )  {  
    return 1000;  
}`

**Comment by FndNur1Labs** [comment]
from graft patch we need change something on block chain

**Comment by FndNur1Labs** [comment]
Fixed

https://github.com/cryptonotefoundation/cryptonote/issues/277

**Comment by FndNur1Labs** [comment]
possible win32 is oldest one on `common` so need updates to `_win32` same as `ANDROID` to `_ANDROID`

**Comment by Shiro20** [comment]
dust is used and unmixable need

**Comment by Shiro20** [comment]
paradigm they keep post!

https://github.com/cryptonotefoundation/cryptonote/pull/28#issuecomment-401327689

this engine old

**Comment by FndNur1Labs** [comment]
yes they keep and issue same. and this move on V3.0.7 jump off!

**Comment by Shiro20** [comment]
bump off ok!fixed...
